{
 "title": "fdb status",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Database Is Available",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 1 },
   "targets": [
    { "expr": "database_available_gauge", "legendFormat": "Database Available" }
   ]
  },
  {
   "title": "Database Locked",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 1 },
   "targets": [
    { "expr": "database_locked_gauge", "legendFormat": "Database Locked" }
   ]
  },
  {
   "title": "Clients",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "clients_number_gauge" }
   ]
  },
  {
   "title": "Commit Latency Statistics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "commit_latency_statistics_gauge{measure=\"median\"}",
     "legendFormat": "Median"
    },
    {
     "expr": "commit_latency_statistics_gauge{measure=\"p25\"}",
     "legendFormat": "p25"
    },
    {
     "expr": "commit_latency_statistics_gauge{measure=\"p90\"}",
     "legendFormat": "p90"
    },
    {
     "expr": "commit_latency_statistics_gauge{measure=\"p95\"}",
     "legendFormat": "p95"
    },
    {
     "expr": "commit_latency_statistics_gauge{measure=\"p99\"}",
     "legendFormat": "p99"
    },
    {
     "expr": "commit_latency_statistics_gauge{measure=\"p99.9\"}",
     "legendFormat": "p99.9"
    }
   ]
  },
  {
   "title": "Read Latency Statistics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 7 },
   "targets": [
    {
     "expr": "read_latency_statistics_gauge{measure=\"median\"}",
     "legendFormat": "Median"
    },
    {
     "expr": "read_latency_statistics_gauge{measure=\"p25\"}",
     "legendFormat": "p25"
    },
    {
     "expr": "read_latency_statistics_gauge{measure=\"p90\"}",
     "legendFormat": "p90"
    },
    {
     "expr": "read_latency_statistics_gauge{measure=\"p95\"}",
     "legendFormat": "p95"
    },
    {
     "expr": "read_latency_statistics_gauge{measure=\"p99\"}",
     "legendFormat": "p99"
    },
    {
     "expr": "read_latency_statistics_gauge{measure=\"p99.9\"}",
     "legendFormat": "p99.9"
    }
   ]
  },
  { "title": "Workload", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Operations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "operations_gauge{type=\"read_requests\"}",
     "legendFormat": "Read Requests"
    },
    {
     "expr": "operations_gauge{type=\"reads\"}",
     "legendFormat": "Reads"
    },
    {
     "expr": "operations_gauge{type=\"writes\"}",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 16 },
   "targets": [
    {
     "expr": "transactions_gauge{status=\"started\"}",
     "legendFormat": "Transactions started"
    },
    {
     "expr": "transactions_gauge{status=\"committed\"}",
     "legendFormat": "Transactions committed"
    }
   ]
  },
  {
   "title": "Transaction Conflicts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 15, "y": 16 },
   "targets": [
    {
     "expr": "transactions_gauge{status=\"conflicted\"}",
     "legendFormat": "Transactions conflicted"
    }
   ]
  },
  {
   "title": "Keys Read",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 22 },
   "targets": [
    { "expr": "keys_read_gauge", "legendFormat": "Keys Read" }
   ]
  },
  {
   "title": "Data",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 22 },
   "targets": [
    {
     "expr": "bytes_RW_gauge{operation=\"read\"}",
     "legendFormat": "Bytes Read"
    },
    {
     "expr": "bytes_RW_gauge{operation=\"written\"}",
     "legendFormat": "Bytes Written"
    }
   ]
  },
  { "title": "QoS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Performance Limited By",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "performance_limited_by_gauge", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "Released Transactions per Second",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 29 },
   "targets": [
    {
     "expr": "released_transactions_per_second_gauge{type=\"released_transactions\"}",
     "legendFormat": "Released transactions per second"
    },
    {
     "expr": "released_transactions_per_second_gauge{type=\"batch_released_transactions\"}",
     "legendFormat": "Batch released transactions per second"
    }
   ]
  },
  {
   "title": "Storage Server Durability Lag",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 29 },
   "targets": [
    {
     "expr": "storage_server_durability_lag_gauge{type=\"limiting\"}",
     "legendFormat": "Limiting"
    },
    {
     "expr": "storage_server_durability_lag_gauge{type=\"worst\"}",
     "legendFormat": "Worst"
    }
   ]
  },
  {
   "title": "Batch Performance Limited By",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "batch_performance_limited_by_gauge",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Transactions per Second Limit",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 35 },
   "targets": [
    {
     "expr": "transactions_per_second_limit_gauge{type=\"transactions_limit\"}",
     "legendFormat": "Transactions per second limit"
    },
    {
     "expr": "transactions_per_second_limit_gauge{type=\"batch_transactions_limit\"}",
     "legendFormat": "Batch transactions per second limit"
    }
   ]
  },
  {
   "title": "Storage Server Data Lag",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 35 },
   "targets": [
    {
     "expr": "storage_server_data_lag_gauge{type=\"limiting\"}",
     "legendFormat": "Limiting"
    },
    {
     "expr": "storage_server_data_lag_gauge{type=\"worst\"}",
     "legendFormat": "Worst"
    }
   ]
  },
  {
   "title": "Log Server Queue",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 41 },
   "targets": [
    { "expr": "log_server_queue_gauge", "legendFormat": "Worst" }
   ]
  },
  {
   "title": "Storage Server Queue",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 41 },
   "targets": [
    {
     "expr": "storage_server_queue_gauge{type=\"limiting\"}",
     "legendFormat": "Limiting"
    },
    {
     "expr": "storage_server_queue_gauge{type=\"worst\"}",
     "legendFormat": "Worst"
    }
   ]
  },
  { "title": "Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "State",
   "type": "stat",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "data_state_gauge", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "Moving Data Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 14, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(moving_data_total_written_bytes_gauge[30s])",
     "legendFormat": "Moving Data Rate"
    }
   ]
  },
  {
   "title": "Total Disk Used",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_disk_used_bytes_gauge" }
   ]
  },
  {
   "title": "Total KV Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_kv_size_bytes_gauge" }
   ]
  },
  {
   "title": "Moving Data in Queue Bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 14, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "moving_data_in_queue_bytes_gauge",
     "legendFormat": "Moving Data in Queue Bytes"
    }
   ]
  },
  {
   "title": "Log Server Least Operating Space",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "least_operating_space_bytes_log_server_gauge"
    }
   ]
  },
  {
   "title": "Storage Server Least Operating Space",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "least_operating_space_bytes_storage_server_gauge"
    }
   ]
  },
  {
   "title": "Moving Data in Flight Bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 14, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "moving_data_in_flight_bytes_gauge",
     "legendFormat": "Moving Data in Flight Bytes"
    }
   ]
  },
  {
   "title": "System KV Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_kv_size_bytes_gauge" }
   ]
  },
  {
   "title": "Average Partition Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "average_partition_size_bytes_gauge"
    }
   ]
  },
  {
   "title": "Partitions Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 14, "y": 66 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "partitions_count_gauge" }
   ]
  },
  { "title": "Processes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Processes",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "sum(class_type_gauge) by (address,classType)",
     "legendFormat": "Class"
    },
    {
     "expr": "sum(cpu_usage_gauge) by (address)",
     "legendFormat": "CPU"
    },
    {
     "expr": "sum(memory_used_bytes_gauge) by (address)",
     "legendFormat": "Memory"
    },
    {
     "expr": "sum(memory_used_bytes_gauge / memory_limit_bytes_gauge) by (address)",
     "legendFormat": "Memory Used"
    },
    {
     "expr": "sum(rate(total_disk_reads_gauge[30s]) + rate(total_disk_writes_gauge[30s])) by (address)",
     "legendFormat": "Disk IO"
    },
    {
     "expr": "sum (disk_used_gauge) by (address)",
     "legendFormat": "Disk Used"
    },
    {
     "expr": "sum(disk_utilization_gauge) by (address)",
     "legendFormat": "Disk Utilization"
    },
    {
     "expr": "sum(network_megabits_sent_rate_gauge + network_megabits_received_rate_gauge) by (address)",
     "legendFormat": "Network IO"
    },
    {
     "expr": "sum (network_current_connections_gauge) by (address)",
     "legendFormat": "Network Connections"
    },
    {
     "expr": "sum(runloop_utilization_gauge) by (address)",
     "legendFormat": "Run Loop Utilization"
    }
   ]
  }
 ]
}