apiVersion: v1
kind: Secret
metadata:
  name: fdb-exporter
  namespace: fdb-monitoring
data:
  fdb-cluster-data: SE1CMVJmanM6UUZTb2lkUXo4cU5PQ3k0c1NSU29BeGhCVU1CWHZZQk5ANTEuMTc4LjY2LjIxOjQ1MDAsNTEuMTc4Ljc4LjEyNTo0NTAwLDIxNy4xODIuMTMzLjIyNzo0NTAw